### PR TITLE
feat: migration of the db

### PR DESCRIPTION
**Pull request by zhyang216**
added a new migration named `create_schemas` with `up.sql` and `down.sql`,
enabling the prompt `diesel migration run` to create our database automatically
@grorge123

### CODE REVIEW

**Comment by grorge123** [comment]
Do you mind I directly modify your code?

**Comment by zhyang216** [comment]
Sure, I appreciate your help in improving the code.

**Comment by grorge123** [comment]
Main Changes
1. Comment backend api not requires schema, which will be completed later.
2. Change FOREIGN KEY CONSTRAINT to column level
4. Chamge float to BIGINT
5. Split balance from portfolios
6. Change table order for REFERENCE dependency

If you think this change is not reasonable, please let me know.
@zhyang216

**Comment by zhyang216** [comment]
I checked all the changes, LGTM.
@grorge123

**Pull request merged**
